id = "example"
version = "1.0.0"
displayName = "Example Extension"
description = "This is an example extension."
icon = "icon.png"
author = "Author Name"
minGameVersion = "1.6.0"
mainClass = "example.Main"
hasInjectInfo = true
supportedPlatforms = ["android", "desktop"]